'use client';
import {RestoringAlertContent} from './focus';
import {useEffect,useRef,useState} from 'react';
import {Plus,Users,ArrowLeft,ChevronRight,MoreHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {type ReadingClass,type Classroom,type Book,type Assignment,metrics,classReadings,readingStatus} from '@/lib/classroom/types';
import {Form,Field,Modal,type Mutate} from './forms';
import {Blank,Cover,AssignmentTable,Activity,StatusFilter,SearchField,formatDate} from './common';
import {CreateStudent} from './students';
import {DeadlineForm} from './details';
import {reconcileMembers} from './membership-draft';
import {useClassroomRefresh} from './sync';
export function ClassForm({group,mutate,close,onSaved}:{group?:ReadingClass;mutate:Mutate;close:()=>void;onSaved?:(id:string)=>void}){
 const[version,setVersion]=useState(group?.version);return <Modal title={group?'Editar turma':'Criar turma'} description="" close={close}><Form onCancel={close} label={group?'Salvar alterações':'Criar turma'} onConflict={()=>setVersion(group?.version)} submit={async f=>{const r=await mutate({action:'saveClass',id:group?.id,version,name:f.get('name'),description:f.get('description')||''});onSaved?.(String(r.id));close();}}><Field label="Nome da turma" id="class-name"><Input id="class-name" name="name" required maxLength={100} defaultValue={group?.name} placeholder="Ex.: 6º Ano A" autoFocus/></Field><details className="optional-fields" open={!!group?.description}><summary>Descrição (opcional)</summary><Field label="Descrição" id="class-description"><Textarea id="class-description" name="description" maxLength={1000} defaultValue={group?.description}/></Field></details></Form></Modal>;
}
export function MembersForm({group,data,mutate,close}:{group:ReadingClass;data:Classroom;mutate:Mutate;close:()=>void}){
 const current=data.classMembers.filter(m=>m.classId===group.id).map(m=>m.studentId);
 const[original,setOriginal]=useState(current),[selected,setSelected]=useState(current),[query,setQuery]=useState(''),[version,setVersion]=useState(group.version),[review,setReview]=useState(false),[creating,setCreating]=useState(false);
 const added=selected.filter(id=>!original.includes(id)),removed=original.filter(id=>!selected.includes(id));
 const readings=data.classBooks.filter(b=>b.classId===group.id),late=readings.filter(b=>b.deadline&&b.deadline<data.today).length;
 const refresh=useClassroomRefresh(),[needsRefresh,setNeedsRefresh]=useState(false),[refreshError,setRefreshError]=useState(''),[refreshing,setRefreshing]=useState(false),failedSnapshot=useRef(data);
 const reconcile=(snapshot:Classroom)=>{const next=reconcileMembers(original,selected,snapshot,group.id);setOriginal(next.original);setSelected(next.selected);setVersion(next.version);setReview(false);setNeedsRefresh(false);setRefreshError('');};
 const recover=async()=>{const snapshot=await refresh();if(!snapshot)throw new Error('Não foi possível atualizar a turma. Sua seleção foi mantida.');reconcile(snapshot);};
 useEffect(()=>{if(needsRefresh&&data!==failedSnapshot.current){try{reconcile(data);}catch(e){setRefreshError((e as Error).message);}}},[data,needsRefresh]);
 if(creating)return <CreateStudent data={data} mutate={mutate} initialClassIds={[group.id]} onCreated={(_id,snapshot)=>{if(snapshot){try{reconcile(snapshot);return;}catch(e){setRefreshError((e as Error).message);}}failedSnapshot.current=data;setNeedsRefresh(true);}} close={()=>setCreating(false)}/>;
 return <Modal title="Alunos da turma" description={group.name} close={close}><Form label={review?'Confirmar alterações':'Salvar alunos'} submitDisabled={needsRefresh} onConflict={recover} onCancel={close} submit={async()=>{if(removed.length&&!review){setReview(true);return;}await mutate({action:'saveMembers',classId:group.id,studentIds:selected,version});close();}}>
 {needsRefresh&&<div className="notice" role="status"><p>Aluno criado. Atualize a lista antes de salvar os alunos da turma. Sua seleção foi mantida.</p>{refreshError&&<p role="alert">{refreshError}</p>}<Button type="button" variant="outline" disabled={refreshing} onClick={async()=>{setRefreshing(true);try{await recover();}catch(e){setRefreshError((e as Error).message);}finally{setRefreshing(false);}}}>{refreshing?'Atualizando…':'Atualizar lista'}</Button></div>}
 {review?<><p>{removed.length} aluno(s) sairão desta turma. Leituras, acesso às leituras anteriores e histórico serão preservados.</p><p>A turma ficará com {selected.length} aluno(s).</p><Button type="button" variant="outline" onClick={()=>setReview(false)}>Revisar seleção</Button></>:<><SearchField value={query} onChange={setQuery} placeholder="Buscar nome ou matrícula…"/><div className="student-picker">{data.students.filter(s=>`${s.name} ${s.enrollment||''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(s=><label key={s.id}><Checkbox checked={selected.includes(s.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,s.id]:ids.filter(id=>id!==s.id))}/><span>{s.name}<small>{s.enrollment?`Matrícula ${s.enrollment}`:'Acesso anterior'}{s.active===0?' · Conta desativada':''}</small></span></label>)}</div>{!data.students.length&&<p>Nenhum aluno cadastrado. Crie a primeira conta nesta turma.</p>}<Button type="button" variant="outline" data-focus-key="members-create-student" onClick={()=>setCreating(true)}><Plus/>Criar aluno</Button><small>{selected.length} selecionado(s)</small></>}
 {added.length>0&&readings.length>0&&<div className="notice">Cada novo aluno receberá automaticamente {readings.length} leitura(s).{late>0&&` ${late} já têm prazo vencido.`}</div>}
 </Form></Modal>;
}
export function ClassList({data,query='',archived=false,onOpen}:{data:Classroom;query?:string;archived?:boolean;onOpen?:(id:string)=>void}){
 const groups=data.classes.filter(c=>!!c.archivedAt===archived&&c.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 return <><div className="classes-grid">{groups.map(c=>{const m=metrics(classReadings(data,c.id));return <a className="class-card" href={`/professor/turmas/${c.id}`} onClick={e=>{if(onOpen&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey){e.preventDefault();onOpen(c.id);}}} key={c.id}><div className="class-card-heading"><span className="class-icon"><Users/></span><ChevronRight size={18}/></div><h3>{c.name}</h3>{c.description&&<p>{c.description}</p>}<small>{data.classMembers.filter(s=>s.classId===c.id).length} alunos · {data.classBooks.filter(b=>b.classId===c.id).length} livros</small>{m.total?<><div className="class-progress"><strong>{m.average}%</strong><span>progresso dos alunos atuais</span></div><Progress value={m.average}/><div className="class-card-footer"><span>{m.completed} concluídas</span>{m.late>0&&<span>{m.late} atrasadas</span>}</div></>:<p className="muted">Sem leituras</p>}</a>;})}</div>{!groups.length&&<Blank title={query?'Nenhuma turma encontrada':archived?'Nenhuma turma arquivada':'Nenhuma turma criada'} description={query?'Tente outro nome.':archived?undefined:'Crie uma turma para começar.'}/>}</>;
}
export function ClassDetails({group,data,mutate,tab='books',bookId,filter='all',scope='current',onTab,onBook,onFilter,onScope,onAssign,onReading,onStudent,onBack,onDeleted}:{group:ReadingClass;data:Classroom;mutate:Mutate;tab?:string;bookId:string|null;filter?:string;scope?:string;onTab:(v:string)=>void;onBook:(id:string|null)=>void;onFilter:(v:string)=>void;onScope:(v:string)=>void;onAssign:(book?:Book)=>void;onReading:(a:Assignment)=>void;onStudent:(id:string)=>void;onBack:()=>void;onDeleted:()=>void}){
 const[modal,setModal]=useState<'edit'|'members'|'archive'|'restore'|'delete'|null>(null),[deadline,setDeadline]=useState(false);
 const readings=classReadings(data,group.id),allReadings=classReadings(data,group.id,true),m=metrics(readings),members=data.classMembers.filter(c=>c.classId===group.id),students=data.students.filter(s=>members.some(m=>m.studentId===s.id));
 const books=data.classBooks.filter(b=>b.classId===group.id).map(cb=>({assignment:cb,book:data.books.find(v=>v.id===cb.bookId)})).filter((b):b is {assignment:typeof b.assignment;book:Book}=>!!b.book);
 const selected=books.find(b=>b.book.id===bookId),visible=(scope==='history'?allReadings:readings).filter(a=>(!selected||a.bookId===selected.book.id)&&(filter==='all'||readingStatus(a)===filter));
 return <><Button variant="ghost" className="back-button" onClick={onBack}><ArrowLeft size={18}/>Turmas</Button><div className="page-heading"><div><h1>{group.name}</h1><p>{students.length} alunos{group.archivedAt?' · Arquivada':''}</p>{group.description&&<p>{group.description}</p>}</div><div className="inline-actions"><Button disabled={!!group.archivedAt} onClick={()=>onAssign()}><Plus/>Atribuir livro</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="icon" aria-label="Opções da turma"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>setModal('edit')}>Editar turma</DropdownMenuItem><DropdownMenuItem onSelect={()=>setModal(group.archivedAt?'restore':'archive')}>{group.archivedAt?'Restaurar turma':'Arquivar turma'}</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={()=>setModal('delete')}>Excluir turma</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>
 <div className="class-toolbar"><Tabs value={tab} onValueChange={v=>{onTab(v);setDeadline(false);}}><TabsList><TabsTrigger value="books">Livros</TabsTrigger><TabsTrigger value="students">Alunos</TabsTrigger><TabsTrigger value="activity">Atividades</TabsTrigger></TabsList></Tabs>{tab==='students'&&<Button variant="outline" disabled={!!group.archivedAt} onClick={()=>setModal('members')}><Users/>Adicionar ou remover alunos</Button>}</div>
 {tab==='books'&&(selected?<section className="surface"><div className="section-heading"><div><Button variant="ghost" onClick={()=>{onBook(null);setDeadline(false);}}><ArrowLeft/>Livros da turma</Button><h2>{selected.book.title}</h2><p>{!selected.assignment.deadlineInitialized?'Prazo coletivo pendente':selected.assignment.deadline?`Até ${formatDate(selected.assignment.deadline)}`:'Sem prazo'}</p></div><Button variant="outline" onClick={()=>setDeadline(v=>!v)}>Alterar prazo da turma</Button></div>
 {!selected.assignment.deadlineInitialized&&<div className="notice"><p>Há prazos antigos diferentes. Defina o prazo coletivo para permitir a entrada de novos alunos.</p><ul>{[...new Set(allReadings.filter(a=>a.bookId===selected.book.id).map(a=>a.deadline))].map(date=><li key={date||'none'}>{date?formatDate(date):'Sem prazo'}: {allReadings.filter(a=>a.bookId===selected.book.id&&a.deadline===date).length} leitura(s)</li>)}</ul></div>}
 {deadline&&<div className="deadline-editor"><DeadlineForm key={selected.assignment.id} id={selected.assignment.id} deadline={selected.assignment.deadline} version={selected.assignment.version} collective uninitialized={!selected.assignment.deadlineInitialized} participants={allReadings.filter(a=>a.bookId===selected.book.id).length} mutate={mutate} onSaved={()=>setDeadline(false)}/></div>}
 <div className="class-toolbar"><Tabs value={scope} onValueChange={onScope}><TabsList><TabsTrigger value="current">Alunos atuais</TabsTrigger><TabsTrigger value="history">Histórico completo</TabsTrigger></TabsList></Tabs><StatusFilter value={filter} onChange={onFilter}/></div><AssignmentTable items={visible} onOpen={onReading} memberIds={students.map(s=>s.id)} context="book" hideOrigin/></section>:books.length?<><p className="muted scope-note">Progresso dos alunos que estão nesta turma.</p><div className="reading-grid">{books.map(({book:b,assignment:cb})=>{const bm=metrics(readings.filter(a=>a.bookId===b.id));return <button className="class-book-card" key={cb.id} onClick={()=>onBook(b.id)}><Cover book={b} small/><div><h3>{b.title}</h3><p>{b.author}</p><strong>{bm.total?`${bm.average}% de progresso`:'Sem alunos com leitura'}</strong>{bm.total>0&&<Progress value={bm.average}/>}<small>{bm.completed} de {bm.total} leituras concluídas</small>{bm.late>0&&<small className="is-late">{bm.late} atrasadas</small>}<small>{cb.deadline?`Até ${formatDate(cb.deadline)}`:'Sem prazo'}</small><span>Ver alunos <ChevronRight size={16}/></span></div></button>;})}</div></>:<Blank title="Nenhum livro atribuído" description="Escolha um livro para esta turma." action={<Button disabled={!!group.archivedAt} onClick={()=>onAssign()}>Atribuir livro</Button>}/>)}
 {tab==='students'&&<><div className="students-grid">{students.map(s=>{const sm=metrics(readings.filter(a=>a.studentId===s.id));return <button className="student-card" key={s.id} onClick={()=>onStudent(s.id)}><span className="avatar">{s.name.slice(0,2).toUpperCase()}</span><h3>{s.name}</h3><small>Matrícula {s.enrollment||'não cadastrada'}</small><p>{sm.completed} de {sm.total} leituras concluídas</p>{sm.total>0&&<Progress value={sm.average}/>}</button>;})}</div>{!students.length&&<Blank title="Adicione os alunos" description="Selecione alunos existentes ou crie suas contas aqui." action={<Button disabled={!!group.archivedAt} onClick={()=>setModal('members')}><Plus/>Adicionar alunos</Button>}/>}</>}
 {tab==='activity'&&<section className="surface"><Activity events={data.events.filter(e=>allReadings.some(a=>a.id===e.assignmentId))} onOpen={id=>{const a=allReadings.find(r=>r.id===id);if(a)onReading(a);}}/></section>}

 {modal==='edit'&&<ClassForm group={group} mutate={mutate} close={()=>setModal(null)}/>}{modal==='members'&&<MembersForm group={group} data={data} mutate={mutate} close={()=>setModal(null)}/>}
 {(modal==='archive'||modal==='restore'||modal==='delete')&&<AlertDialog open onOpenChange={v=>!v&&setModal(null)}><RestoringAlertContent><AlertDialogHeader><AlertDialogTitle>{modal==='archive'?'Arquivar turma?':modal==='restore'?'Restaurar turma?':'Excluir turma?'}</AlertDialogTitle><AlertDialogDescription>{modal==='delete'?'A turma sairá da gestão. Leituras e histórico serão preservados.':modal==='archive'?'Novas atribuições e alterações de alunos ficarão bloqueadas. As leituras atuais continuam disponíveis.':'A turma voltará a aceitar alunos e novas atribuições.'}</AlertDialogDescription></AlertDialogHeader><Form onCancel={()=>setModal(null)} label="Confirmar" submit={async()=>{await mutate({action:'classState',classId:group.id,state:modal,version:group.version});setModal(null);if(modal==='delete')onDeleted();}}><strong>{group.name}</strong></Form></RestoringAlertContent></AlertDialog>}
 </>;
}
