'use client';
import {useState,type ReactNode} from 'react';
import {BookOpen,CalendarDays,CheckCircle2,ChevronRight,Clock3,AlertCircle} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {percentage,readingStatus,statusLabels,unitLabels,type Assignment,type Book,type ReadingEvent} from '@/lib/classroom/types';
export function Brand(){return <a href="/" className="brand"><img src="/favicon.svg" width="42" height="42" alt=""/><span><strong>Trilha</strong><small>de Leitura</small></span></a>;}
export function formatDate(v:string|null,time=false){if(!v)return '—';return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',...(time?{hour:'2-digit',minute:'2-digit'}:{year:'numeric'}),timeZone:'America/Sao_Paulo'}).format(new Date(v.length===10?v+'T12:00:00Z':v));}
export function relative(v:string|null){if(!v)return 'Sem atividade';const n=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/86400000));return n===0?'Hoje':n===1?'Ontem':`Há ${n} dias`;}
export function Cover({book,small=false}:{book:Pick<Book,'title'|'coverUrl'>;small?:boolean}){const[failed,setFailed]=useState<string|null>(null);return <div className={`cover ${small?'cover-small':''}`}>{book.coverUrl&&failed!==book.coverUrl?<img key={book.coverUrl} src={book.coverUrl} alt={`Capa de ${book.title}`} onError={()=>setFailed(book.coverUrl)} loading="lazy" referrerPolicy="no-referrer"/>:<><BookOpen/><span>{book.title}</span></>}</div>;}
export function Status({item}:{item:Assignment}){const s=readingStatus(item);const Icon=s==='completed'?CheckCircle2:s==='late'?AlertCircle:s==='reading'?BookOpen:Clock3;return <span className={`status status-${s}`}><Icon size={14}/>{statusLabels[s]}</span>;}
export function Meter({item}:{item:Assignment}){return <div className="meter"><div><span>{item.unit==='percent'?`${item.progress}%`:`${item.progress} / ${item.totalPages} ${unitLabels[item.unit]}`}</span>{item.unit!=='percent'&&<strong>{percentage(item)}%</strong>}</div><Progress value={percentage(item)} aria-label={`${percentage(item)}% concluído`}/></div>;}
export function Blank({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <Empty className="blank"><EmptyHeader><EmptyMedia variant="icon"><BookOpen/></EmptyMedia><EmptyTitle>{title}</EmptyTitle>{description&&<EmptyDescription>{description}</EmptyDescription>}</EmptyHeader>{action}</Empty>;}
export function Origin({item}:{item:Assignment}){return <small className="reading-origin">{item.classId?`${item.className||'Turma'}${item.classDeletedAt?' · turma excluída':item.classArchivedAt?' · arquivada':''}`:'Leitura individual'}</small>;}
export function ReadingCard({item,onOpen}:{item:Assignment;onOpen:(a:Assignment)=>void}){return <article className="reading-card"><div className="reading-card-head"><Cover book={item} small/><div><h3>{item.title}</h3><p>{item.author}</p><small>Prof. {item.teacherName}</small></div></div><Origin item={item}/><Status item={item}/><Meter item={item}/><p className={`deadline ${readingStatus(item)==='late'?'is-late':''}`}><CalendarDays size={16}/>{item.deadline?`Até ${formatDate(item.deadline)}`:'Sem prazo'}</p><Button data-focus-key={`reading-${item.id}`} onClick={()=>onOpen(item)} className="w-full">{item.completedAt?'Ver histórico':'Atualizar progresso'}<ChevronRight size={16}/></Button></article>;}
export function AssignmentTable({items,onOpen,memberIds,context='all',hideOrigin=false}:{items:Assignment[];onOpen:(a:Assignment)=>void;memberIds?:string[];context?:'all'|'book'|'student';hideOrigin?:boolean}){
 if(!items.length)return <Blank title="Nenhuma leitura encontrada" description="As leituras deste grupo aparecerão aqui."/>;
 const identity=(a:Assignment)=><><strong>{context==='student'?a.title:a.studentName}</strong>{context!=='student'&&a.studentEnrollment&&<small>Matrícula {a.studentEnrollment}</small>}{memberIds&&!memberIds.includes(a.studentId)&&<small>Não pertence mais à turma</small>}{context==='all'&&<span>{a.title}</span>}{!hideOrigin&&<Origin item={a}/>}</>;
 return <><div className="reading-rows">{items.map(a=><button key={a.id} className="reading-row" data-focus-key={`reading-${a.id}`} onClick={()=>onOpen(a)}><span className="reading-row-top"><span className="table-name">{identity(a)}</span><ChevronRight size={18}/></span><Meter item={a}/><span className="reading-row-bottom"><Status item={a}/><span>{a.deadline?`Até ${formatDate(a.deadline)}`:'Sem prazo'}</span></span><small className="muted">{relative(a.updatedAt)}</small></button>)}</div><div className="assignment-table desktop-table"><Table><TableHeader><TableRow><TableHead>{context==='student'?'Livro':context==='book'?'Aluno':'Aluno / livro'}</TableHead><TableHead>Progresso</TableHead><TableHead>Status</TableHead><TableHead>Última atividade</TableHead><TableHead>Prazo</TableHead></TableRow></TableHeader><TableBody>{items.map(a=><TableRow key={a.id}><TableCell><button className="table-name" data-focus-key={`reading-${a.id}`} onClick={()=>onOpen(a)}>{identity(a)}</button></TableCell><TableCell><div className="table-meter"><Progress value={percentage(a)}/><strong>{percentage(a)}%</strong></div></TableCell><TableCell><Status item={a}/></TableCell><TableCell>{relative(a.updatedAt)}</TableCell><TableCell>{a.deadline?formatDate(a.deadline):'Sem prazo'}</TableCell></TableRow>)}</TableBody></Table></div></>;
}
export function Activity({events,onOpen,own=false,compact=false}:{events:ReadingEvent[];onOpen?:(id:string)=>void;own?:boolean;compact?:boolean}){if(!events.length)return <p className="muted padded">Nenhuma atualização registrada.</p>;return <ol className="activity-list">{events.map(e=><li key={e.id}><span className="activity-dot"><BookOpen size={16}/></span><div>{!compact&&<button data-focus-key={`activity-${e.id}`} disabled={!onOpen} onClick={()=>onOpen?.(e.assignmentId)}>{!own&&<><strong>{e.studentName}</strong>{e.studentEnrollment&&<small> · {e.studentEnrollment}</small>} · </>}{e.title}</button>}<p>{e.kind==='correction'?'Correção: ':''}{e.previousProgress} → {e.progress} {unitLabels[e.unit]}{e.progress===e.totalPages?' · Concluída':''}</p>{e.kind==='correction'&&<small>{e.actorName}: {e.reason}</small>}{e.deadlineRecorded===1&&<small>Prazo ao concluir: {e.completionDeadline?formatDate(e.completionDeadline):'Sem prazo'}</small>}<time dateTime={e.createdAt}>{formatDate(e.createdAt,true)}</time></div></li>)}</ol>;}
export function StatusFilter({value,onChange}:{value:string;onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="status-filter" aria-label="Filtrar por status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem>{Object.entries(statusLabels).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select>;}
export function SearchField({value,onChange,placeholder='Buscar título ou autor…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <Input type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder}/>;}
