'use client';
import {useState} from 'react';
import {CheckCircle2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {AlertDialog,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Sheet,SheetClose,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {Classroom,Assignment} from '@/lib/classroom/types';
import {unitLabels} from '@/lib/classroom/types';
import {readingDeadlineHistory} from '@/lib/classroom/deadline-history';
import {Activity,Cover,Meter,Status,Origin,formatDate} from './common';
import {Form,Field,type Mutate} from './forms';
import {useReturnFocus,RestoringAlertContent} from './focus';
export function DeadlineForm({id,deadline,version,collective=false,uninitialized=false,participants=1,mutate,onSaved}:{id:string;deadline:string|null;version:number;collective?:boolean;uninitialized?:boolean;participants?:number;mutate:Mutate;onSaved?:()=>void}){
 const[value,setValue]=useState(deadline||''),[review,setReview]=useState(false),[base,setBase]=useState(version);
 return <Form label={collective?(review?'Confirmar prazo':'Revisar prazo'):'Salvar prazo'} onConflict={()=>{setBase(version);setReview(false);}} submit={async()=>{if(collective&&!review){setReview(true);return;}await mutate({action:collective?'classDeadline':'deadline',id,deadline:value||null,version:base,confirmed:true});setReview(false);onSaved?.();}}>
 {review?<div className="notice"><p><strong>{uninitialized?'Prazos anteriores diferentes':deadline?formatDate(deadline):'Sem prazo'} → {value?formatDate(value):'Sem prazo'}</strong></p><p>O novo prazo valerá para {participants} leitura(s) desta atribuição, incluindo alunos que saíram da turma. Conclusões serão preservadas.</p><Button type="button" variant="ghost" onClick={()=>setReview(false)}>Editar data</Button></div>:<><Field label="Prazo (opcional)" id="edit-deadline"><Input id="edit-deadline" type="date" value={value} onChange={e=>setValue(e.target.value)}/></Field>{collective&&<small className="muted">Um prazo para todos os alunos desta atribuição.</small>}</>}
 </Form>;
}
export function ReadingDetails({item,data,mutate,close,onStudent}:{item:Assignment;data:Classroom;mutate:Mutate;close:()=>void;onStudent?:(id:string)=>void}){
 const restore=useReturnFocus();
 const teacher=data.user?.role==='teacher';const[value,setValue]=useState(String(item.progress)),[version,setVersion]=useState(item.version),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editDeadline,setEditDeadline]=useState(false),[correct,setCorrect]=useState(false);
 const save=async()=>{const result=await mutate({action:'progress',id:item.id,progress:Number(value),version});if(!result.unchanged)setVersion(v=>v+1);};
 const deadlineEvents=readingDeadlineHistory(data.deadlineEvents,item);
 return <Sheet open onOpenChange={v=>!v&&close()}><SheetContent className="detail-sheet" onCloseAutoFocus={restore} showCloseButton={false}><SheetClose asChild><Button variant="ghost" size="icon" className="overlay-close" aria-label="Fechar leitura"><X/></Button></SheetClose><SheetHeader><SheetTitle>{item.title}</SheetTitle><SheetDescription>{teacher?`${item.studentName} · Matrícula ${item.studentEnrollment||'não cadastrada'}`:`Professor: ${item.teacherName}`}</SheetDescription></SheetHeader><div className="detail-content"><div className="detail-book"><Cover book={item} small/><div><p>{item.author}</p><Origin item={item}/><Status item={item}/></div></div><Meter item={item}/><p className="deadline">{item.deadline?`Prazo: ${formatDate(item.deadline)}`:'Sem prazo'}</p>
 {!teacher&&(item.completedAt?<div className="completion-note"><CheckCircle2/><strong>Leitura concluída em {formatDate(item.completedAt)}.</strong></div>:<section className="detail-section progress-editor"><h3>Onde você chegou?</h3><Form label={Number(value)===item.totalPages?'Finalizar leitura':'Salvar progresso'} onConflict={()=>setVersion(item.version)} submit={async()=>{if(Number(value)===item.totalPages){setConfirm(true);return;}await save();}}><Field label={item.unit==='pages'?'Página atual':item.unit==='chapters'?'Capítulos concluídos':'Percentual concluído'} id="progressValue" name="progress"><Input id="progressValue" type="number" required inputMode="numeric" min={item.progress} max={item.totalPages} value={value} onChange={e=>setValue(e.target.value)}/></Field><small className="muted">Seu professor recebe o progresso assim que ele é salvo.</small></Form></section>)}
 {teacher&&<div className="inline-actions">{onStudent&&<Button variant="outline" onClick={()=>onStudent(item.studentId)}>Ver aluno</Button>}<Button variant="outline" onClick={()=>setEditDeadline(v=>!v)}>{item.classId?'Alterar prazo da turma':'Alterar prazo'}</Button></div>}
 {editDeadline&&teacher&&<section className="detail-section"><h3>{item.classId?`Prazo · ${item.className}`:'Prazo individual'}</h3><DeadlineForm id={item.classAssignmentId||item.id} deadline={item.deadline} version={item.classAssignmentVersion??item.version} collective={!!item.classId} uninitialized={!!item.classAssignmentId&&!data.classBooks.find(c=>c.id===item.classAssignmentId)?.deadlineInitialized} participants={data.assignments.filter(a=>a.classAssignmentId===item.classAssignmentId).length} mutate={mutate} onSaved={()=>setEditDeadline(false)}/></section>}
 <details className="history-disclosure" open={!!item.completedAt}><summary>Histórico da leitura</summary><dl className="reading-dates"><div><dt>Atribuída em</dt><dd>{formatDate(item.assignedAt)}</dd></div><div><dt>Início</dt><dd>{formatDate(item.startedAt)}</dd></div><div><dt>Última atualização</dt><dd>{formatDate(item.updatedAt,true)}</dd></div>{item.completedAt&&<div><dt>Conclusão</dt><dd>{formatDate(item.completedAt)}</dd></div>}</dl><Activity events={data.events.filter(e=>e.assignmentId===item.id)} own compact/>{deadlineEvents.length>0&&<><h3>Alterações de prazo</h3><ul className="deadline-history">{deadlineEvents.map(e=><li key={e.id}><span>{e.scope==='consolidation'?'Prazo coletivo definido: ':`${e.previousDeadline?formatDate(e.previousDeadline):'Sem prazo'} → `}{e.deadline?formatDate(e.deadline):'Sem prazo'}</span><small>{e.scope==='individual'?'Registro da leitura':e.scope==='consolidation'?'Consolidação dos prazos da turma':'Alteração para toda a turma'}</small><small>{formatDate(e.createdAt,true)}</small></li>)}</ul></>}</details>
 {teacher&&<section className="correction-section"><Button variant="ghost" onClick={()=>setCorrect(v=>!v)}>Corrigir registro de progresso</Button>{correct&&<CorrectionForm key={item.id} item={item} mutate={mutate} close={()=>setCorrect(false)}/>}</section>}
 </div><AlertDialog open={confirm} onOpenChange={setConfirm}><RestoringAlertContent open={confirm}><AlertDialogHeader><AlertDialogTitle>Concluir esta leitura?</AlertDialogTitle><AlertDialogDescription>Você está registrando o final de “{item.title}”. Seu professor verá a conclusão e a data.</AlertDialogDescription></AlertDialogHeader>{error&&<><p role="alert" className="form-error">{error}</p><Button variant="outline" onClick={()=>{setVersion(item.version);setConfirm(false);setError('');}}>Revisar progresso atual</Button></>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Voltar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();setBusy(true);setError('');try{await save();setConfirm(false);}catch(err){setError((err as Error).message);setVersion(item.version);}finally{setBusy(false);}}}>{busy?'Concluindo…':'Concluir leitura'}</AlertDialogAction></AlertDialogFooter></RestoringAlertContent></AlertDialog></SheetContent></Sheet>;
}
function CorrectionForm({item,mutate,close}:{item:Assignment;mutate:Mutate;close:()=>void}){const[version,setVersion]=useState(item.version);return <Form label="Salvar correção" onCancel={close} onConflict={()=>setVersion(item.version)} submit={async f=>{await mutate({action:'correctProgress',id:item.id,progress:Number(f.get('progress')),reason:f.get('reason'),version,confirmed:true});close();}}><p>O registro original será preservado. Reduzir o progresso abaixo do total reabre a leitura.</p><Field label={`Progresso correto (${unitLabels[item.unit]})`} id="correct-progress"><Input id="correct-progress" name="progress" type="number" inputMode="numeric" min={0} max={item.totalPages} required defaultValue={item.progress}/></Field><Field label="Motivo da correção" id="correction-reason"><Textarea id="correction-reason" name="reason" required minLength={3} maxLength={300}/></Field></Form>;}
