'use client';
import { useState, useContext, createContext, Children, isValidElement, cloneElement, type ReactElement, type FormEvent, type ReactNode } from 'react';
import { LoaderCircle,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Dialog,DialogClose,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import type {Book,Classroom,AssignmentPreview} from '@/lib/classroom/types';
import {ClassForm,MembersForm} from './classes';
import {CreateStudent} from './students';
import {useReturnFocus,focusOverlayStart} from './focus';
export type MutationResult=Record<string,unknown>&{snapshot?:Classroom|null};
export type Mutate=(command:Record<string,unknown>)=>Promise<MutationResult>;
const FormErrors=createContext<Record<string,string>>({});
export function Form({submit,children,label='Salvar',busyLabel='Salvando…',onCancel,onConflict,submitDisabled=false}:{submit:(data:FormData,form:HTMLFormElement)=>Promise<unknown>;children:ReactNode;label?:string;busyLabel?:string;onCancel?:()=>void;onConflict?:()=>void|Promise<void>;submitDisabled?:boolean}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string>>({}),[conflict,setConflict]=useState(false);
 async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||submitDisabled)return;const form=e.currentTarget,data=new FormData(form);setBusy(true);setError('');setFields({});setConflict(false);try{await submit(data,form);}catch(err){const problem=err as {message?:string;fields?:Record<string,string>;status?:number};setError(problem.message||'Não foi possível salvar. Tente novamente.');setFields(problem.fields||{});setConflict(problem.status===409);requestAnimationFrame(()=>form.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());}finally{setBusy(false);}}
 return <FormErrors.Provider value={fields}><form onSubmit={onSubmit} className="reader-form" aria-busy={busy}><fieldset disabled={busy}>{children}</fieldset>{error&&<p className="form-error" role="alert">{error}</p>}{conflict&&onConflict&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await onConflict();setConflict(false);setError('Dados atualizados. Confira os campos antes de salvar.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Revisar dados atuais</Button>}<div className="form-actions">{onCancel&&<Button type="button" variant="outline" onClick={onCancel} disabled={busy}>Fechar</Button>}<Button type="submit" disabled={busy||submitDisabled}>{busy&&<LoaderCircle className="animate-spin"/>}{busy?busyLabel:label}</Button></div></form></FormErrors.Provider>;
}
export function Field({label,id,name,children}:{label:string;id:string;name?:string;children:ReactNode}){
 const errors=useContext(FormErrors);const input=Children.toArray(children).find(c=>isValidElement(c)&&(c.props as {name?:string}).name) as ReactElement<{name?:string}>|undefined;
 const error=errors[name||input?.props.name||id];
 return <div className="form-field"><Label htmlFor={id}>{label}</Label>{Children.map(children,c=>isValidElement(c)?cloneElement(c as ReactElement<Record<string,unknown>>,{'aria-invalid':!!error,'aria-describedby':error?id+'-error':undefined}):c)}{error&&<small id={id+'-error'} className="field-error">{error}</small>}</div>;
}
export function Modal({title,description,close,children}:{title:string;description:string;close:()=>void;children:ReactNode}){const restore=useReturnFocus();return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="reader-dialog" showCloseButton={false} onOpenAutoFocus={focusOverlayStart} onCloseAutoFocus={restore}><DialogClose asChild><Button variant="ghost" size="icon" className="overlay-close" aria-label="Fechar formulário"><X/></Button></DialogClose><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription className={description?undefined:'sr-only'}>{description||title}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>;}
export function Onboard({mutate}:{mutate:Mutate}){return <div className="entry-page"><div className="entry-card"><img src="/favicon.svg" width="56" height="56" alt=""/><p className="eyebrow">ESPAÇO DO PROFESSOR</p><h1>Comece sua turma de leitura</h1><p>Configure seu perfil para cadastrar alunos e compartilhar leituras.</p><Form label="Criar perfil de professor" submit={async f=>{await mutate({action:'onboard',name:f.get('name'),role:'teacher'});window.location.assign('/professor');}}><Field label="Nome completo" id="name"><Input id="name" name="name" autoComplete="name" required minLength={2} maxLength={60}/></Field></Form><a href="/entrar">Sou aluno · Entrar com matrícula</a></div></div>;}
export function BookForm({book,mutate,close,onSaved,locked=false}:{book:Book|null;mutate:Mutate;close:()=>void;onSaved?:(id:string)=>void;locked?:boolean}){
 const[unit,setUnit]=useState<Book['unit']>(book?.unit||'pages'),[cover,setCover]=useState(book?.coverUrl||'');
 return <Modal title={book?'Editar livro':'Adicionar livro'} description="" close={close}><Form onCancel={close} label={book?'Salvar alterações':'Adicionar livro'} submit={async f=>{const r=await mutate({action:'saveBook',id:book?.id,title:f.get('title'),author:f.get('author'),totalPages:unit==='percent'?100:locked?book?.totalPages:Number(f.get('totalPages')),unit,coverUrl:cover});onSaved?.(String(r.id));close();}}>
 <Field label="Título" id="title"><Input name="title" id="title" required maxLength={160} defaultValue={book?.title}/></Field>
 <Field label="Autor ou autora" id="author"><Input name="author" id="author" required maxLength={160} defaultValue={book?.author}/></Field>
 <div className="form-two"><Field label="Medir progresso em" id="unit"><Select disabled={locked} value={unit} onValueChange={v=>setUnit(v as Book['unit'])}><SelectTrigger id="unit"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pages">Páginas</SelectItem><SelectItem value="chapters">Capítulos</SelectItem><SelectItem value="percent">Percentual</SelectItem></SelectContent></Select></Field>
 {unit!=='percent'&&<Field label={unit==='chapters'?'Total de capítulos':'Total de páginas'} id="totalPages"><Input id="totalPages" name="totalPages" type="number" min={1} max={100000} inputMode="numeric" required defaultValue={book?.totalPages} key={unit} disabled={locked}/></Field>}</div>
 {locked&&<small className="muted">Unidade e total preservados porque este livro já foi atribuído.</small>}
 <Field label="Link da capa (opcional)" id="coverUrl"><Input id="coverUrl" name="coverUrl" type="url" pattern="https://.*" placeholder="https://…" value={cover} onChange={e=>setCover(e.target.value)}/></Field>
 {cover.startsWith('https://')&&<div className="cover-preview"><img key={cover} src={cover} alt="Prévia da capa" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;}}/><small>Se a imagem não carregar, o título será usado como capa.</small></div>}
 </Form></Modal>;
}
export function AssignForm({book,data,mutate,close,classId,studentId}:{book?:Book;data:Classroom;mutate:Mutate;close:()=>void;classId?:string;studentId?:string}){
 const[mode,setMode]=useState<'class'|'individual'>(studentId?'individual':'class'),[bookId,setBookId]=useState(book?.id||''),[selected,setSelected]=useState<string[]>(classId?[classId]:studentId?[studentId]:[]),[query,setQuery]=useState(''),[deadline,setDeadline]=useState(''),[preview,setPreview]=useState<AssignmentPreview|null>(null),[chooseRecipients,setChooseRecipients]=useState(!classId&&!studentId),[chooseBook,setChooseBook]=useState(!book),[creating,setCreating]=useState<'book'|'class'|'student'|null>(null),[membersId,setMembersId]=useState<string|null>(null);
 const options=mode==='class'?data.classes.filter(c=>!c.archivedAt):data.students;
 const chosen=options.filter(o=>selected.includes(o.id)),chosenBook=data.books.find(b=>b.id===bookId);
 const existing=mode==='class'?data.classBooks.filter(b=>selected.includes(b.classId)&&b.bookId===bookId):[];
 const draft={bookId,mode,classIds:mode==='class'?selected:[],studentIds:mode==='individual'?selected:[],deadline:deadline||null};
 if(creating==='book')return <BookForm book={null} mutate={mutate} close={()=>setCreating(null)} onSaved={id=>{setBookId(id);setChooseBook(false);}}/>;
 if(creating==='class')return <ClassForm mutate={mutate} close={()=>setCreating(null)} onSaved={id=>{setSelected(ids=>[...ids,id]);setMembersId(id);}}/>;
 if(creating==='student')return <CreateStudent data={data} mutate={mutate} close={()=>setCreating(null)} onCreated={id=>setSelected(ids=>[...ids,id])}/>;
 const memberGroup=data.classes.find(c=>c.id===membersId);if(memberGroup)return <MembersForm group={memberGroup} data={data} mutate={mutate} close={()=>setMembersId(null)}/>;
 return <Modal title={preview?'Confirmar atribuição':'Atribuir livro'} description="" close={close}><Form onCancel={close} busyLabel={preview?'Atribuindo…':'Preparando resumo…'} label={preview?(preview.newReadings?'Confirmar atribuição':'Concluir'):'Revisar atribuição'} submit={async()=>{
  if(!preview){if(!bookId||!selected.length)throw new Error('Escolha o livro e os destinatários.');setPreview(await mutate({action:'previewAssignment',...draft}) as unknown as AssignmentPreview);return;}
  if(!preview.newReadings){close();return;}try{await mutate({action:'distribute',...draft,versions:preview.versions});close();}catch(e){setPreview(null);throw e;}
 }}>
 {preview?<><div className="distribution-review"><p><span>Livro</span><strong>{preview.bookTitle}</strong></p><p><span>{mode==='class'?'Turma':'Aluno'}</span><strong>{chosen.map(o=>o.name+('enrollment' in o&&o.enrollment?' · '+o.enrollment:'')).join(', ')}</strong></p><p><span>Alunos</span><strong>{preview.recipients}</strong></p><p><span>Prazo das novas atribuições</span><strong>{deadline?deadline.split('-').reverse().join('/'):'Sem prazo'}</strong></p></div>
 {preview.readings>preview.recipients&&<p className="notice">{preview.readings} leituras independentes: há alunos em mais de uma turma selecionada.</p>}{preview.existingReadings>0&&<p>{preview.existingReadings} leitura(s) já existente(s) serão preservadas.{preview.newReadings>0&&` Serão criadas ${preview.newReadings} novas leituras.`}</p>}
 <Button type="button" variant="outline" onClick={()=>setPreview(null)}>Editar seleção</Button></>:<>
 <div className="section-heading"><h3>{mode==='class'?'Para a turma':'Para o aluno'}</h3>{!chooseRecipients&&<Button type="button" variant="ghost" onClick={()=>setChooseRecipients(true)}>Alterar</Button>}</div>
 {chooseRecipients?<><Input type="search" aria-label={mode==='class'?'Buscar turma':'Buscar nome ou matrícula'} placeholder={mode==='class'?'Buscar turma…':'Buscar nome ou matrícula…'} value={query} onChange={e=>setQuery(e.target.value)}/><div className="student-picker">{options.filter(o=>`${o.name} ${'enrollment' in o?o.enrollment||'':''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(o=><label key={o.id}><Checkbox checked={selected.includes(o.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,o.id]:ids.filter(id=>id!==o.id))}/><span>{o.name}{'enrollment' in o&&o.enrollment&&<small>Matrícula {o.enrollment}</small>}{mode==='class'&&<small>{data.classMembers.filter(m=>m.classId===o.id).length} alunos</small>}</span></label>)}</div><Button type="button" variant="outline" data-focus-key="assign-create-recipient" onClick={()=>setCreating(mode==='class'?'class':'student')}>{mode==='class'?'Criar turma':'Criar aluno'}</Button></>:<p className="context-value">{chosen.map(o=>o.name+('enrollment' in o&&o.enrollment?' · '+o.enrollment:'')).join(', ')}</p>}
 {mode==='class'&&chosen.filter(c=>!data.classMembers.some(m=>m.classId===c.id)).map(c=><div className="notice" key={c.id}>{c.name} ainda não tem alunos. <Button type="button" variant="outline" data-focus-key={`assign-members-${c.id}`} onClick={()=>setMembersId(c.id)}>Adicionar alunos</Button></div>)}
 <Button type="button" variant="ghost" className="alternative-action" onClick={()=>{setMode(mode==='class'?'individual':'class');setSelected([]);setChooseRecipients(true);setQuery('');}}>{mode==='class'?'Atribuir a alunos individualmente':'Atribuir para turma'}</Button>
 {chooseBook?<><Field label="Livro" id="assignment-book"><Select value={bookId} onValueChange={setBookId}><SelectTrigger id="assignment-book"><SelectValue placeholder="Selecione um livro"/></SelectTrigger><SelectContent>{data.books.map(b=><SelectItem key={b.id} value={b.id}>{b.title}</SelectItem>)}</SelectContent></Select></Field><Button type="button" variant="outline" data-focus-key="assign-create-book" onClick={()=>setCreating('book')}>Adicionar livro</Button></>:<div className="section-heading"><div><small>Livro</small><strong className="context-value">{chosenBook?.title}</strong></div><Button type="button" variant="ghost" onClick={()=>setChooseBook(true)}>Alterar</Button></div>}
 <Field label="Prazo (opcional)" id="deadline"><Input id="deadline" type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></Field>
 {existing.length>0&&<p className="notice">Este livro já está atribuído a {existing.length} turma(s) selecionada(s). Os prazos existentes serão mantidos. Para alterá-los, abra o livro na turma.</p>}
 </>}
 </Form></Modal>;
}
export function JoinForm({mutate,close}:{mutate:Mutate;close:()=>void}){return <Modal title="Vincular professor" description="Peça o código de convite ao professor e cole abaixo." close={close}><Form onCancel={close} label="Vincular professor" submit={async f=>{await mutate({action:'join',code:f.get('code')});close();}}><Field label="Código do professor" id="code"><Input name="code" id="code" autoCapitalize="none" autoCorrect="off" spellCheck={false} required minLength={20}/></Field></Form></Modal>;}
export function GoalForm({mutate,close}:{mutate:Mutate;close:()=>void}){return <Modal title="Criar meta pessoal" description="Escolha quantos livros quer concluir em um período." close={close}><Form onCancel={close} label="Criar meta" submit={async f=>{await mutate({action:'saveGoal',title:f.get('title'),targetBooks:Number(f.get('targetBooks')),startDate:f.get('startDate'),endDate:f.get('endDate')});close();}}><Field label="Nome da meta" id="goalTitle"><Input id="goalTitle" name="title" required maxLength={160} placeholder="Minha meta de leitura"/></Field><Field label="Quantidade de livros" id="targetBooks"><Input id="targetBooks" name="targetBooks" type="number" required min={1} max={200} defaultValue={3}/></Field><div className="form-two"><Field label="Início" id="startDate"><Input id="startDate" name="startDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="Conclusão até" id="endDate"><Input id="endDate" name="endDate" type="date" required/></Field></div></Form></Modal>;}
