'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Form,Field} from './forms';
import {Brand} from './common';
import {fetchJson,RequestError} from './client';
async function authRequest(action:string,body:Record<string,unknown>={}){return await fetchJson(`/api/student-auth/${action}`,body) as {redirect:string};}
export async function studentLogout(){await authRequest('logout');window.location.assign('/entrar');}
export function StudentLogin(){const[teacherBusy,setTeacherBusy]=useState(false),[error,setError]=useState('');return <main className="entry-page"><div className="entry-card student-login"><Brand/><p className="eyebrow">ACESSO DO ALUNO</p><h1>Vamos continuar<br/>sua leitura?</h1><p>Entre com a matrícula e a senha informadas pelo professor.</p><Form label="Entrar" busyLabel="Entrando…" submit={async f=>{const result=await authRequest('login',{enrollment:f.get('enrollment'),password:f.get('password')});window.location.assign(result.redirect);}}><Field label="Matrícula" id="enrollment"><Input id="enrollment" name="enrollment" inputMode="numeric" pattern="[0-9]{1,32}" maxLength={32} autoComplete="username" placeholder="Ex.: 202600154" required/></Field><Field label="Senha" id="password"><Input id="password" name="password" type="password" autoComplete="current-password" maxLength={128} required/></Field></Form><p className="muted">Esqueceu sua senha? Peça ao professor para redefini-la.</p>{error&&<p role="alert" className="form-error">{error}</p>}<Button variant="outline" disabled={teacherBusy} onClick={async()=>{setTeacherBusy(true);try{await authRequest('logout');window.location.assign('/signin-with-chatgpt?return_to=/professor');}catch(e){setError((e as Error).message);setTeacherBusy(false);}}}>Sou professor · Entrar com ChatGPT</Button></div></main>;}
export function FirstPassword({name,enrollment}:{name:string;enrollment:string}){return <main className="entry-page"><div className="entry-card student-login"><Brand/><h1>Crie sua nova senha</h1><p>{name} · Matrícula {enrollment}</p><p>Antes de acessar as leituras, substitua a senha inicial. Use pelo menos 8 caracteres.</p><Form label="Salvar senha e continuar" submit={async f=>{const password=String(f.get('password')),confirmation=String(f.get('confirmation'));if(password!==confirmation)throw new RequestError('Confira a confirmação da senha.',400,{confirmation:'As senhas devem ser iguais.'});const result=await authRequest('password',{password,confirmation});window.location.assign(result.redirect);}}><Field label="Nova senha" id="new-password"><Input id="new-password" name="password" type="password" minLength={8} maxLength={128} autoComplete="new-password" required/></Field><Field label="Confirmar nova senha" id="confirm-password" name="confirmation"><Input id="confirm-password" name="confirmation" type="password" minLength={8} maxLength={128} autoComplete="new-password" required/></Field></Form><Button variant="ghost" onClick={()=>void studentLogout()}>Sair desta conta</Button></div></main>;}
