'use client';
import {RestoringAlertContent} from './focus';
import {useState} from 'react';
import {Plus,Search,Users,KeyRound,PenLine,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import type {Classroom,Student} from '@/lib/classroom/types';
import {Form,Field,Modal,type Mutate} from './forms';
import {Blank} from './common';
function StudentFields({student}:{student?:Student}){return <><Field label="Nome completo *" id="student-name"><Input name="name" id="student-name" required minLength={2} maxLength={160} defaultValue={student?.name} autoComplete="off"/></Field>{!student&&<EnrollmentField/>}<details className="optional-fields" open={!!student?.email}><summary>E-mail (opcional)</summary><Field label="E-mail" id="student-email"><Input name="email" id="student-email" type="email" maxLength={254} defaultValue={student?.email||''} autoComplete="off"/></Field></details></>;}
function EnrollmentField(){return <Field label="Número de matrícula *" id="student-enrollment"><Input id="student-enrollment" name="enrollment" inputMode="numeric" pattern="[0-9]{1,32}" maxLength={32} required placeholder="Ex.: 202600154" autoComplete="off"/><small className="muted">Somente números. Zeros no início serão mantidos.</small></Field>;}
function ClassPicker({data,selected,setSelected,includeArchived=false}:{data:Classroom;selected:string[];setSelected:(v:string[])=>void;includeArchived?:boolean}){const list=data.classes.filter(c=>includeArchived||!c.archivedAt);return <div className="student-picker">{list.map(c=><label key={c.id}><Checkbox disabled={!!c.archivedAt} checked={selected.includes(c.id)} onCheckedChange={v=>setSelected(v?[...selected,c.id]:selected.filter(id=>id!==c.id))}/><span>{c.name}{c.archivedAt&&<small>Arquivada · restaure para alterar</small>}</span></label>)}{!list.length&&<p className="muted">Nenhuma turma ativa. Você pode associar o aluno depois.</p>}</div>;}
export function CreateStudent({data,mutate,close,initialClassIds=[],onCreated}:{data:Classroom;mutate:Mutate;close:()=>void;initialClassIds?:string[];onCreated?:(id:string,snapshot:Classroom|null)=>void}){
 const[selected,setSelected]=useState(initialClassIds);
 const assigned=data.classBooks.filter(b=>selected.includes(b.classId)),late=assigned.filter(b=>b.deadline&&b.deadline<data.today).length;
 return <Modal title="Adicionar aluno" description="" close={close}><Form label="Criar aluno" onCancel={close} submit={async(f,form)=>{const r=await mutate({action:'createStudent',name:f.get('name'),enrollment:f.get('enrollment'),email:f.get('email')||'',classIds:selected});if(onCreated){onCreated(String(r.id),r.snapshot??null);close();}else{form.reset();requestAnimationFrame(()=>(form.elements.namedItem('name') as HTMLInputElement)?.focus());}}}>
 <StudentFields/>{initialClassIds.length>0?<><p>Turma: <strong>{data.classes.filter(c=>selected.includes(c.id)).map(c=>c.name).join(', ')||'Nenhuma'}</strong></p><details className="optional-fields"><summary>Alterar turmas</summary><ClassPicker data={data} selected={selected} setSelected={setSelected}/></details></>:<Field label="Turmas (opcional)" id="student-classes"><div id="student-classes"><ClassPicker data={data} selected={selected} setSelected={setSelected}/></div></Field>}
 {assigned.length>0&&<small className="notice">Receberá automaticamente {assigned.length} leitura(s).{late>0&&` ${late} têm prazo vencido.`}</small>}
 <div className="initial-password"><KeyRound size={18}/><span>Senha inicial: <strong>EDU123</strong><small>Troca obrigatória no primeiro acesso.</small></span></div>
 </Form></Modal>;
}
export function StudentsManager({data,onOpen,onCreate,query='',onQuery,group='all',onGroup}:{data:Classroom;onOpen:(id:string)=>void;onCreate:()=>void;query?:string;onQuery:(v:string)=>void;group?:string;onGroup:(v:string)=>void}){
 const list=data.students.filter(s=>`${s.name} ${s.enrollment||''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))&&(group==='all'||(group==='none'?!data.classMembers.some(m=>m.studentId===s.id):data.classMembers.some(m=>m.studentId===s.id&&m.classId===group))));
 const groups=(id:string)=>data.classes.filter(c=>data.classMembers.some(m=>m.classId===c.id&&m.studentId===id)).map(c=>c.name).join(', ')||'Sem turma';
 return <><div className="student-management-toolbar"><Input type="search" aria-label="Buscar nome ou matrícula" placeholder="Buscar nome ou matrícula…" value={query} onChange={e=>onQuery(e.target.value)}/><Select value={group} onValueChange={onGroup}><SelectTrigger aria-label="Filtrar alunos por turma"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas as turmas</SelectItem><SelectItem value="none">Sem turma</SelectItem>{data.classes.map(c=><SelectItem key={c.id} value={c.id}>{c.name}{c.archivedAt?' (arquivada)':''}</SelectItem>)}</SelectContent></Select></div>
 {list.length?<><div className="reading-rows">{list.map(s=><button key={s.id} className="reading-row" onClick={()=>onOpen(s.id)}><strong>{s.name}</strong><span>Matrícula {s.enrollment||'não cadastrada'}</span><small>{groups(s.id)}</small><StudentStatus student={s}/></button>)}</div><section className="surface assignment-table desktop-table"><Table><TableHeader><TableRow><TableHead>Aluno</TableHead><TableHead>Matrícula</TableHead><TableHead>Turmas</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{list.map(s=><TableRow key={s.id}><TableCell><button className="table-name" onClick={()=>onOpen(s.id)}><strong>{s.name}</strong></button></TableCell><TableCell>{s.enrollment||'Não cadastrada'}</TableCell><TableCell>{groups(s.id)}</TableCell><TableCell><StudentStatus student={s}/></TableCell></TableRow>)}</TableBody></Table></section></>:<Blank title={data.students.length?'Nenhum aluno encontrado':'Nenhum aluno cadastrado'} description={data.students.length?'Ajuste a busca ou a turma.':'Informe nome e matrícula para criar a primeira conta.'} action={!data.students.length&&<Button onClick={onCreate}><Plus/>Adicionar aluno</Button>}/>}</>;
}
function StudentStatus({student:s}:{student:Student}){return <span className={`status ${!s.enrollment?'status-pending':s.active?'status-completed':'status-late'}`}>{!s.enrollment?'Acesso anterior':!s.active?'Desativado':s.mustChangePassword?'Ativo · primeiro acesso':'Ativo'}</span>;}
export function StudentManagement({student,data,mutate,onIdChange}:{student:Student;data:Classroom;mutate:Mutate;onIdChange:(id:string)=>void}){
 const[dialog,setDialog]=useState<'edit'|'classes'|'reset'|'active'|'correct'|'enroll'|null>(null);
 const canManage=student.managedBy===data.user?.id||!student.enrollment;
 const groups=data.classes.filter(c=>data.classMembers.some(m=>m.classId===c.id&&m.studentId===student.id));
 return <section className="surface student-account"><div className="student-account-heading"><div><p className="eyebrow">CADASTRO DO ALUNO</p><h2>{student.enrollment?`Matrícula ${student.enrollment}`:'Matrícula ainda não cadastrada'}</h2>{student.email&&<p>{student.email}</p>}</div><StudentStatus student={student}/></div><div className="inline-actions">{canManage&&(student.enrollment?<><Button variant="outline" onClick={()=>setDialog('edit')}><PenLine/>Editar dados</Button><Button variant="outline" onClick={()=>setDialog('reset')}><KeyRound/>Redefinir senha</Button><Button variant="ghost" onClick={()=>setDialog('active')}>{student.active?'Desativar conta':'Reativar conta'}</Button></>:<Button onClick={()=>setDialog('enroll')}>Cadastrar matrícula e acesso</Button>)}</div><div className="student-groups"><div className="section-heading"><h3>Turmas</h3>{<Button variant="outline" onClick={()=>setDialog('classes')}><Users/>Alterar turmas</Button>}</div><div className="class-tags">{groups.map(c=><a key={c.id} href={`/professor/turmas/${c.id}`}>{c.name}{c.archivedAt?' · arquivada':''}</a>)}{!groups.length&&<p className="muted">Este aluno ainda não pertence a uma turma.</p>}</div><p className="muted">Alterar turmas preserva a matrícula, as leituras e todo o histórico.</p></div>{canManage&&student.enrollment&&<Button className="enrollment-correction" variant="ghost" onClick={()=>setDialog('correct')}><ShieldCheck size={16}/>Corrigir matrícula</Button>}
 {dialog==='edit'&&<EditStudent key={`${student.id}-edit`} student={student} mutate={mutate} close={()=>setDialog(null)}/>}
 {dialog==='classes'&&<StudentClasses student={student} data={data} mutate={mutate} close={()=>setDialog(null)}/>}
 {(dialog==='correct'||dialog==='enroll'||dialog==='reset'||dialog==='active')&&<AccountConfirmation kind={dialog} student={student} mutate={mutate} close={()=>setDialog(null)} onIdChange={onIdChange}/>}
 </section>;
}
function EditStudent({student,mutate,close}:{student:Student;mutate:Mutate;close:()=>void}){const[version,setVersion]=useState(student.version);return <Modal title="Editar aluno" description={`Matrícula ${student.enrollment} · O histórico será mantido.`} close={close}><Form onConflict={()=>setVersion(student.version)} onCancel={close} submit={async f=>{await mutate({action:'editStudent',studentId:student.id,name:f.get('name'),email:f.get('email'),version});close();}}><StudentFields student={student}/></Form></Modal>;}
function StudentClasses({student,data,mutate,close}:{student:Student;data:Classroom;mutate:Mutate;close:()=>void}){
 const current=data.classMembers.filter(m=>m.studentId===student.id).map(m=>m.classId);
 const[original,setOriginal]=useState(current),[selected,setSelected]=useState(current),[versions,setVersions]=useState(Object.fromEntries(data.classes.map(c=>[c.id,c.version]))),[review,setReview]=useState(false);
 const added=selected.filter(id=>!original.includes(id)),removed=original.filter(id=>!selected.includes(id));
 const books=data.classBooks.filter(b=>added.includes(b.classId));
 const recover=()=>{setSelected([...new Set([...current.filter(id=>!removed.includes(id)),...added])]);setOriginal(current);setVersions(Object.fromEntries(data.classes.map(c=>[c.id,c.version])));setReview(false);};
 return <Modal title="Alterar turmas" description={`${student.name} · ${student.enrollment||'Acesso anterior'}`} close={close}><Form onCancel={close} onConflict={recover} label={review?'Confirmar alteração':'Salvar turmas'} submit={async()=>{if(removed.length&&!review){setReview(true);return;}await mutate({action:'studentClasses',studentId:student.id,classIds:selected,versions});close();}}>
 {review?<><p>O aluno ficará em: <strong>{data.classes.filter(c=>selected.includes(c.id)).map(c=>c.name).join(', ')||'Nenhuma turma'}</strong>.</p><p>As leituras das turmas anteriores e o histórico serão preservados.</p><Button type="button" variant="outline" onClick={()=>setReview(false)}>Revisar seleção</Button></>:<ClassPicker data={data} selected={selected} setSelected={setSelected} includeArchived/>}
 {books.length>0&&<small className="notice">Receberá as leituras que faltam entre {books.length} livro(s) das novas turmas.{books.some(b=>b.deadline&&b.deadline<data.today)&&' Há prazos já vencidos.'}</small>}
 </Form></Modal>;
}
function AccountConfirmation({kind,student,mutate,close,onIdChange}:{kind:'correct'|'enroll'|'reset'|'active';student:Student;mutate:Mutate;close:()=>void;onIdChange:(id:string)=>void}){const[version,setVersion]=useState(student.version),[enrollment,setEnrollment]=useState<string|null>(null);const title=kind==='correct'?'Corrigir matrícula':kind==='enroll'?'Cadastrar matrícula':kind==='reset'?'Redefinir senha':student.active?'Desativar conta':'Reativar conta';return <AlertDialog open onOpenChange={v=>!v&&close()}><RestoringAlertContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{student.name} · {student.enrollment||'Acesso anterior'}</AlertDialogDescription></AlertDialogHeader><Form onConflict={()=>setVersion(student.version)} onCancel={close} label={(kind==='correct'||kind==='enroll')&&!enrollment?'Revisar matrícula':'Confirmar'} submit={async f=>{if((kind==='correct'||kind==='enroll')&&!enrollment){setEnrollment(String(f.get('enrollment')));return;}const result=await mutate({action:kind==='correct'?'correctEnrollment':kind==='enroll'?'enrollStudent':kind==='reset'?'resetStudentPassword':'studentActive',studentId:student.id,enrollment,version,active:!student.active,confirmed:true});if(result.id)onIdChange(String(result.id));close();}}>{kind==='correct'||kind==='enroll'?enrollment?<><p>Confirma {kind==='correct'?`a alteração de ${student.enrollment} para`:'o cadastro da matrícula'} <strong>{enrollment}</strong>?</p><p>A mesma conta manterá todas as leituras, turmas e histórico. {kind==='correct'?'As sessões abertas serão encerradas. A senha atual será mantida.':'O acesso passará a ser feito por matrícula e senha inicial EDU123.'}</p><Button type="button" variant="outline" onClick={()=>setEnrollment(null)}>Voltar e corrigir</Button></>:<EnrollmentField/>:kind==='reset'?<p>A senha voltará para <strong>EDU123</strong>. As sessões abertas serão encerradas e o aluno deverá criar uma nova senha pessoal. Matrícula e histórico serão mantidos.</p>:<p>{student.active?'O aluno deixará de acessar o aplicativo e suas sessões serão encerradas.':'O aluno poderá acessar novamente com sua senha atual.'} As leituras e o histórico serão preservados.</p>}</Form></RestoringAlertContent></AlertDialog>;}
